/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TipsRouteImport } from './routes/tips'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScanWebsiteRouteImport } from './routes/scan.website'
import { Route as ScanQrRouteImport } from './routes/scan.qr'
import { Route as ScanMessageRouteImport } from './routes/scan.message'
import { Route as ScanLinkRouteImport } from './routes/scan.link'
import { Route as ScanFileRouteImport } from './routes/scan.file'

const TipsRoute = TipsRouteImport.update({
  id: '/tips',
  path: '/tips',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanWebsiteRoute = ScanWebsiteRouteImport.update({
  id: '/scan/website',
  path: '/scan/website',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanQrRoute = ScanQrRouteImport.update({
  id: '/scan/qr',
  path: '/scan/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanMessageRoute = ScanMessageRouteImport.update({
  id: '/scan/message',
  path: '/scan/message',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanLinkRoute = ScanLinkRouteImport.update({
  id: '/scan/link',
  path: '/scan/link',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanFileRoute = ScanFileRouteImport.update({
  id: '/scan/file',
  path: '/scan/file',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/tips': typeof TipsRoute
  '/scan/file': typeof ScanFileRoute
  '/scan/link': typeof ScanLinkRoute
  '/scan/message': typeof ScanMessageRoute
  '/scan/qr': typeof ScanQrRoute
  '/scan/website': typeof ScanWebsiteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/tips': typeof TipsRoute
  '/scan/file': typeof ScanFileRoute
  '/scan/link': typeof ScanLinkRoute
  '/scan/message': typeof ScanMessageRoute
  '/scan/qr': typeof ScanQrRoute
  '/scan/website': typeof ScanWebsiteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/tips': typeof TipsRoute
  '/scan/file': typeof ScanFileRoute
  '/scan/link': typeof ScanLinkRoute
  '/scan/message': typeof ScanMessageRoute
  '/scan/qr': typeof ScanQrRoute
  '/scan/website': typeof ScanWebsiteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/tips'
    | '/scan/file'
    | '/scan/link'
    | '/scan/message'
    | '/scan/qr'
    | '/scan/website'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/tips'
    | '/scan/file'
    | '/scan/link'
    | '/scan/message'
    | '/scan/qr'
    | '/scan/website'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/tips'
    | '/scan/file'
    | '/scan/link'
    | '/scan/message'
    | '/scan/qr'
    | '/scan/website'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  TipsRoute: typeof TipsRoute
  ScanFileRoute: typeof ScanFileRoute
  ScanLinkRoute: typeof ScanLinkRoute
  ScanMessageRoute: typeof ScanMessageRoute
  ScanQrRoute: typeof ScanQrRoute
  ScanWebsiteRoute: typeof ScanWebsiteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tips': {
      id: '/tips'
      path: '/tips'
      fullPath: '/tips'
      preLoaderRoute: typeof TipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/website': {
      id: '/scan/website'
      path: '/scan/website'
      fullPath: '/scan/website'
      preLoaderRoute: typeof ScanWebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/qr': {
      id: '/scan/qr'
      path: '/scan/qr'
      fullPath: '/scan/qr'
      preLoaderRoute: typeof ScanQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/message': {
      id: '/scan/message'
      path: '/scan/message'
      fullPath: '/scan/message'
      preLoaderRoute: typeof ScanMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/link': {
      id: '/scan/link'
      path: '/scan/link'
      fullPath: '/scan/link'
      preLoaderRoute: typeof ScanLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/file': {
      id: '/scan/file'
      path: '/scan/file'
      fullPath: '/scan/file'
      preLoaderRoute: typeof ScanFileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  TipsRoute: TipsRoute,
  ScanFileRoute: ScanFileRoute,
  ScanLinkRoute: ScanLinkRoute,
  ScanMessageRoute: ScanMessageRoute,
  ScanQrRoute: ScanQrRoute,
  ScanWebsiteRoute: ScanWebsiteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
